In [1]:
import numpy as np

In [2]:
a = np.full(10, -1, np.int32)

In [3]:
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32)

In [5]:
a.size

10

In [6]:
a.resize(5)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [7]:
np.resize(a, 5)

array([-1, -1, -1, -1, -1], dtype=int32)

In [8]:
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32)

In [10]:
np.resize(a, 15, -2)

TypeError: _resize_dispatcher() takes 2 positional arguments but 3 were given

In [11]:
np.pad(a, 15)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0], dtype=int32)

In [12]:
np.resize(a, 5)

array([-1, -1, -1, -1, -1], dtype=int32)

In [17]:
np.concatenate( (a, np.full(5, 2)) )

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  2,  2,  2,  2,  2])

In [18]:
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32)

In [19]:
a.dtype

dtype('int32')

In [20]:
b = [1, 2, 3, 4]

In [21]:
b[0:3]

[1, 2, 3]

In [22]:
b + [1, 2, 3]

[1, 2, 3, 4, 1, 2, 3]

In [23]:
b += [1, 2, 3]

In [24]:
b

[1, 2, 3, 4, 1, 2, 3]

In [32]:
c = 5

In [33]:
x = c if c is not None else -1

In [34]:
x

5

In [35]:
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32)

In [36]:
a[3] = 5

In [37]:
a

array([-1, -1, -1,  5, -1, -1, -1, -1, -1, -1], dtype=int32)

In [38]:
a = 3

In [39]:
a

3

In [41]:
a = np.full(3, -1)

In [42]:
a[:] = 3

In [43]:
a

array([3, 3, 3])